---
- include: pre_requisite.yml
  when: install_docker

- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- include: start_docker_keystone.yml

- include: check.yml

- include: configure.yml
