---
- include: pre_requisite.yml
  when: install_docker
- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- include: fetch_configs.yml
- include: checks.yml
- include: start_docker_proxy.yml
